name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        cd bash-4.3.30
        ./configure
        make lint

  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      fail-fast: false

    steps:
    - uses: actions/checkout@v3

    - name: configure and make
      run: |
        cd bash-4.3.30
        bash -c "./configure CFLAGS=-Wno-implicit-function-declaration"
        bash -c "make bash2pyengine"

    - name: run-all
      run: |
        cd tests/bash_tests
        bash -c "sh ./run-all"
