name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        ./configure
        make lint

  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      fail-fast: false

    steps:
    - uses: actions/checkout@v3

    - name: configure and make
      run: |
        bash -c './configure CFLAGS="-Wno-implicit-function-declaration -Wno-implicit-int"'
        bash -c "make bash2py"

    - name: run-all
      run: |
        cd tests/bash_tests
        bash -c "sh ./run-all"
